# fly.toml app configuration file generated for mem-stack on 2023-06-09T18:32:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mem-stack"
primary_region = "bos"

[env]
  PORT = "8080"



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
